[config]
default_to_workspace = true
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.default]
alias = "serve"

[tasks.cargo-format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-all]
script = '''
leptosfmt .
cargo fmt --all
cargo clippy --fix -- -D warnings
'''

[tasks.check]
script = '''
leptosfmt --check .
cargo fmt --all --check
cargo clippy -- -D warnings
'''

[tasks.leptos-format]
install_crate = { crate_name = "leptosfmt", version = "0.1.13" }
command = "leptosfmt"
args = ["."]

[tasks.format]
dependencies = ["cargo-format", "leptos-format"]

[tasks.fmt]
alias = "format"

[tasks.get-sitemap]
command = "sh"
args = [
    "-c",
    "rm -f assets/sitemap.xml && wget -S -P assets https://github.com/Phosphorus-M/sitemap-rustico/releases/download/latest/sitemap.xml",
]

[tasks.prebuild]
condition = { env_not_set = ["IN_NIX_SHELL"] }
command = "npx"
args = ["tailwindcss", "-i", "./input.css", "-o", "./style/output.css"]

[tasks.prebuild-nixdev]
condition = { env_set = ["IN_NIX_SHELL"] }
command = "tailwindcss"
args = ["-i", "./input.css", "-o", "./style/output.css"]

[tasks.build]
dependencies = ["get-sitemap", "prebuild", "prebuild-nixdev"]
install_crate = { crate_name = "cargo-leptos", binary = "cargo", test_arg = [
    "leptos",
    "--version",
], version = "0.2.16" }
command = "cargo"
args = ["leptos", "serve", "-r"]

[tasks.serve]
dependencies = ["prebuild", "prebuild-nixdev"]
install_crate = { crate_name = "cargo-leptos", binary = "cargo", test_arg = [
    "leptos",
    "--version",
], version = "0.2.16" }
command = "cargo"
args = ["leptos", "watch", "--features", "development", "--hot-reload"]
